# Generated by Django 5.1 on 2026-05-13 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie / description')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name="Annees d'experience")),
                ('hourly_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tarif horaire (FCFA)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Photo de profil')),
                ('city', models.CharField(default='Abidjan', max_length=100, verbose_name='Ville')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Note moyenne')),
                ('total_jobs', models.PositiveIntegerField(default=0, verbose_name='Missions terminees')),
                ('is_verified_by_admin', models.BooleanField(default=False, verbose_name='Verifie par admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'ARTISAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil artisan',
                'verbose_name_plural': 'Profils artisans',
                'ordering': ['-created_at'],
            },
        ),
    ]
