# Generated by Django 6.0.5 on 2026-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_artisanprofile'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='artisans', to='catalog.category', verbose_name='Categories de metiers'),
        ),
    ]
