# Generated by Django 6.0.5 on 2026-05-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_artisanprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='Ex: 🔧 ou wrench (nom lucide-icon)', max_length=50, verbose_name='Icone (emoji ou nom)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='accounts.artisanprofile', verbose_name='Artisan')),
            ],
            options={
                'verbose_name': 'Photo de portfolio',
                'verbose_name_plural': 'Photos de portfolio',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
